apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wd-martin
  annotations:
    cert-manager.io/cluster-issuer: ${CERT_ISSUER_PROD}
    traefik.ingress.kubernetes.io/router.middlewares: ${NAMESPACE}-wd-martin-header@kubernetescrd
spec:
  rules:
    - host: tiles.${ENV_SUBDOMAIN}${WODORE_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wd-martin
                port:
                  number: 3000
  tls:
    - secretName: wd-martin-${ENVIRONMENT}-tls
      hosts:
        - tiles.${ENV_SUBDOMAIN}${WODORE_HOST}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: wd-martin-header
spec:
  headers:
    customResponseHeaders:
      X-Cache-Status: "Traefik"
      Cache-Control: "public, max-age=1800"
    accessControlAllowMethods:
      - GET
      - OPTIONS
    accessControlAllowOriginList:
      - https://${ENV_SUBDOMAIN}${WODORE_HOST}
    accessControlMaxAge: 100
