apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-martin-sync-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v3
  resources:
    requests:
      storage: 1Gi
