# UNSEAL SECRET for openbao
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

secretGenerator:
  - name: openbao-unseal-1-key
    files:
      - unseal-1.key=unseal-1.key # run: 'openssl rand -out unseal.key 32' to get key
    options:
      disableNameSuffixHash: true
