# IMMICH NAMESPACE ================================= immich ==
apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
# PRESISTEND VOLUME DATA ====
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    #path: /home/tobias/mnt/k8s/immich/library
    path: /mnt/kubernetes/volumes/immich/server/data
    type: DirectoryOrCreate
---
# PRESISTEND VOLUME EXTERNAL LIBRARY ====
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    #path: /home/tobias/mnt/k8s/immich/library
    path: /mnt/kubernetes/volumes/immich/server/external
    type: DirectoryOrCreate
---
# PRESISTEND VOLUME CLAIM DATA ====
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: local-path   # or whatever StorageClass you use in k3s
  volumeName: immich-data-pv
---
# PRESISTEND VOLUME CLAIM EXTERNAL ====
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: local-path   # or whatever StorageClass you use in k3s
  volumeName: immich-external-pv
---
# IMMICH HELM ================================ immich-server ==
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: immich
spec:
  chart: immich
  repo: https://immich-app.github.io/immich-charts
  version: 0.10.0
  targetNamespace: immich
  valuesContent: ""  # Will be replaced by kustomize, changes are made in `immich-values.yaml`
---
# IMMICH INGRESS =============================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
spec:
  tls:
    - hosts:
        - $DOMAIN
  rules:
    - host: $DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ENV-immich-server # use correct name in kustomization
                port:
                  number: 2283
