apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami
  annotations:
    cert-manager.io/cluster-issuer: ${CERT_ISSUER_PROD}
spec:
  rules:
    - host: stats.${ENV_SUBDOMAIN}${WODORE_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: umami
                port:
                  number: 3000
    - host: stats.${ENV_SUBDOMAIN}${BURGDEV_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: umami
                port:
                  number: 3000
  tls:
    - hosts:
        - stats.${ENV_SUBDOMAIN}${WODORE_HOST}
        - stats.${ENV_SUBDOMAIN}${BURGDEV_HOST}
      secretName: umami-tls
