apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: umami-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-${NAMESPACE}
  destination:
    name: umami-envvars
    create: true
    transformation:
      excludeRaw: true
      #excludes: ["^_.*"]
  path: apps/umami/${NAMESPACE}
