# k8s/infrastructure/rclone/helm-release.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: csi-driver-rclone
  namespace: kube-system
  annotations:
    helmcharts.cattle.io/managed-by: helm-controller
spec:
  chart: csi-driver-rclone
  repo: oci://registry-1.docker.io/veloxpack/csi-driver-rclone-charts
  version: 0.1.0
  targetNamespace: rclone-system
  createNamespace: true
