# https://github.com/perfectra1n/volsync (with kopia support)
# forked from https://github.com/volsync/volsync
# see PR: https://github.com/backube/volsync/pull/1723 
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: volsync
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://perfectra1n.github.io/volsync/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  targetNamespace: ${NAMESPACE}
  chart:
    spec:
      chart: volsync
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: volsync
      version: "0.16.*"
  valuesFrom:
    - kind: ConfigMap
      name: volsync-values
      valuesKey: values.yaml
  interval: 1h0s
