apiVersion: v1
kind: ConfigMap
metadata:
  name: kopia-policies
data:
  # check if therer are any issues:
  # kubectl get configmap kopia-policies -o jsonpath='{.data.global-policy\.json}' | jq .
  # Global policy file - Applied via 'kopia policy set --global'
  global-policy.json: |
    {
      "retention": {
        "keepLatest": 5,
        "keepHourly": 2,
        "keepDaily": 3,
        "keepWeekly": 4,
        "keepMonthly": 10,
        "keepAnnual": 0,
        "ignoreIdenticalSnapshots": true
      },
      "compression": {
        "compressor": "zstd",
        "neverCompress": [".7z",".7Z",".alz",".ALZ",".bz",".BZ",".bz2",".BZ2",".cab",".CAB",".cbr",".CBR",".cbz",".CBZ",".deb",".DEB",".dl_",".DL_",".dsft",".DSFT",".ex_",".EX_",".gz",".GZ",".jar",".JAR",".lmza",".LMZA",".lzo",".LZO",".mpkg",".MPKG",".msi",".MSI",".msp",".MSP",".msu",".MSU",".pet",".PET",".rar",".RAR",".sft",".SFT",".sit",".SIT",".sitx",".SITX",".sy_",".SY_",".tgz",".TGZ",".tbz2",".TBZ2",".txz",".TXZ",".war",".WAR",".wim",".WIM",".xar",".XAR",".xz",".XZ",".zip",".ZIP",".zipx",".ZIPX",".zst",".ZST",".3gp",".3GP",".3g2",".3G2",".aa3",".AA3",".aac",".AAC",".aif",".AIF",".ape",".APE",".flac",".FLAC",".gsm",".GSM",".iff",".IFF",".m4a",".M4A",".mp3",".MP3",".mpa",".MPA",".mpc",".MPC",".ra",".RA",".ofr",".OFR",".ofs",".OFS",".ogg",".OGG",".opus",".OPUS",".wma",".WMA",".wv",".WV",".asf",".ASF",".asx",".ASX",".avi",".AVI",".bsf",".BSF",".divx",".DIVX",".f4v",".F4V",".flv",".FLV",".hdmov",".HDMOV",".m2p",".M2P",".m4v",".M4V",".mkv",".MKV",".mov",".MOV",".mp4",".MP4",".mpg",".MPG",".mpeg",".MPEG",".mts",".MTS",".ogm",".OGM",".ogv",".OGV",".rm",".RM",".swf",".SWF",".trp",".TRP",".ts",".TS",".vob",".VOB",".webm",".WEBM",".wmv",".WMV",".wtv",".WTV",".emz",".EMZ",".gif",".GIF",".j2c",".J2C",".jpeg",".JPEG",".jpg",".JPG",".nef",".NEF",".pamp",".PAMP",".pdn",".PDN",".png",".PNG",".pspimage",".PSPIMAGE",".tif",".TIF",".tiff",".TIFF",".dng",".DNG",".cr2",".CR2",".dmg",".DMG",".tib",".TIB",".aes",".AES",".axx",".AXX",".gpg",".GPG",".hc",".HC",".kdbx",".KDBX",".tc",".TC",".tpm",".TPM",".fve",".FVE",".apk",".APK",".eftx",".EFTX",".sdg",".SDG",".thmx",".THMX",".vsix",".VSIX",".vsv",".VSV",".wmz",".WMZ",".xpi",".XPI",".eot",".EOT",".woff",".WOFF",".bik",".BIK",".mpq",".MPQ",".docx",".DOCX",".docm",".DOCM",".dotm",".DOTM",".dotx",".DOTX",".epub",".EPUB",".graffle",".GRAFFLE",".hxs",".HXS",".max",".MAX",".mobi",".MOBI",".mshc",".MSHC",".odp",".ODP",".ods",".ODS",".odt",".ODT",".otp",".OTP",".ots",".OTS",".ott",".OTT",".pages",".PAGES",".pptx",".PPTX",".stw",".STW",".trf",".TRF",".webarchive",".WEBARCHIVE",".xlsx",".XLSX",".xlsm",".XLSM",".xlsb",".XLSB",".xps",".XPS",".d",".D",".dess",".DESS",".i",".I",".idx",".IDX",".nupkg",".NUPKG",".pack",".PACK",".swz",".SWZ",".lz",".LZ",".lz4",".LZ4",".z",".Z",".s7z",".S7Z",".ace",".ACE",".arj",".ARJ",".rpm",".RPM"]
      }
    }
  # Repository config file
  repository.config: |
    {
      "enableActions": true,
      "actionCommandTimeout": "10m",
      "ecc": "REED-SOLOMON",
      "eccOverheadPercent": 2
    }

