---
# SMTP
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openbao-configs-smtp-burgdev
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: configs-kv-all
  destination:
    name: openbao-configs-smtp-burgdev
    create: true
    transformation:
      excludeRaw: true
      includes: ["SMTP_.*"]
  path: configs/smtp_burgdev
---
# HEARTBEATS
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: openbao-configs-heatbeats
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: configs-kv-all
  destination:
    name: openbao-configs-heartbeats
    create: true
    transformation:
      excludeRaw: true
      includes: ["BEAT_.*"]
  path: configs/heartbeats
