# docu from fork: https://perfectra1n.github.io/volsync/usage/kopia/index.html
# IMMICH LIBRARY - volsync
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${CLUSTER}-immich-library # 'username' for kopia
  namespace: ${NAMESPACE}
spec:
  sourcePVC: immich-library-pvc-v1
  trigger:
    schedule: "*/2 * * * *"
    #manual: backup-01
  kopia:
    repository: volsync-kopia-webdav-secrets
    policyConfig:
      configMapName: kopia-policies

    # Overwrite Retention Policy
    retain:
      hourly: 24
      daily: 4
      weekly: 2
      monthly: 1
      yearly: 0

    #actions:
    #  beforeSnapshot: |
    #    echo "[Auto] Start at $(date)" >> /data/backup.log

    #  afterSnapshot: |
    #    echo "[Auto] Finished at $(date)" >> /data/backup.log

    # Use snapshot for point-in-time consistency
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 0 # root
      runAsGroup: 0 # root
      fsGroup: 0
---
# EXTERNAL Library - volsync
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${CLUSTER}-immich-external # 'username' for kopia
  namespace: ${NAMESPACE}
spec:
  sourcePVC: immich-external-pvc-v1
  trigger:
    schedule: "*/3 * * * *"
    #manual: backup-01
  kopia:
    repository: volsync-kopia-webdav-secrets
    policyConfig:
      configMapName: kopia-policies

    # Overwrite Retention Policy
    retain:
      hourly: 24
      daily: 4
      weekly: 2
      monthly: 1
      yearly: 0

    #actions:
    #  beforeSnapshot: |
    #    echo "[Auto] Start at $(date)" >> /data/backup.log

    #  afterSnapshot: |
    #    echo "[Auto] Finished at $(date)" >> /data/backup.log

    # Use snapshot for point-in-time consistency
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 0 # root
      runAsGroup: 0 # root
      fsGroup: 0
---
# DATABASE - volsync
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${CLUSTER}-immich-postgres # 'username' for kopia
  namespace: ${NAMESPACE}
spec:
  sourcePVC: immich-postgres-1
  trigger:
    schedule: "*/4 * * * *"
    #manual: backup-01
  kopia:
    repository: volsync-kopia-webdav-secrets
    policyConfig:
      configMapName: kopia-policies

    # Overwrite Retention Policy
    retain:
      hourly: 24
      daily: 4
      weekly: 2
      monthly: 1
      yearly: 0

    #actions:
    #  beforeSnapshot: |
    #    echo "[Auto] Start at $(date)" >> /data/backup.log

    #  afterSnapshot: |
    #    echo "[Auto] Finished at $(date)" >> /data/backup.log

    # Use snapshot for point-in-time consistency
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 26 # postgres
      runAsGroup: 26 # tape
      fsGroup: 26
