apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  #app.kubernetes.io/name: immich
  app.kubernetes.io/component: immich
  app.kubernetes.io/environment: ${ENVIRONMENT}
  app.kubernetes.io/part-of: apps
  app.kubernetes.io/managed-by: flux
resources:
  - postgres.yaml
  - pvcs.yaml
  - helmrelease.yaml

configMapGenerator:
  - name: immich-values
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
