apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich.yaml
  - immich-db.yaml
  - immich-cache.yaml

# Add name prefix and suffix
#namePrefix: immich-
#nameSuffix: -v1

# Common labels for all resources
# TODO: do not use labels selectors!
#labels:
#- includeSelectors: false
#  pairs:
#    app: immich
#    verson: v1
# set label in ENV
# app.kubernetes.io/instance=local-immich
# env: 
# ...
