apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-local-media-v0
provisioner: local.csi.openebs.io
parameters:
  storageType: lvm
  volgroup: ${VG_NAME:-openebs-vg}
  fsType: xfs
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - noatime