apiVersion: v1
kind: Secret
metadata:
  name: rclone-kdrive-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  configData: |
    [kdrive]
    type = webdav
    url = ${WEBDAV_URL}
    vendor = other
    user = ${WEBDAV_USERNAME}
    pass = ${WEBDAV_PASSWORD}