# used to manage policies in openbao
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-config-manager
---
# used by init scripts to create and manage secrets in openbao
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-secrets-manager
