apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-volsync-dev
  namespace: flux-system # do not change!
spec:
  interval: 1h0s
  path: "./k8s/infrastructure/volsync/base"
  dependsOn:
  - name: helm-volsync-system
  - name: infra-openebs-system 
  prune: true
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: burgdev-burginfra
  postBuild:
    substitute:
      NAME: "volsync"
      NAMESPACE: "development"
      COMPONENT: "backup"
      ENVIRONMENT: "dev"
