apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: map-data-elevation
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-data-v3
  resources:
    requests:
      storage: ${MAP_DATA_ELEVATION_STORAGE_SIZE:-5Gi}
