apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: map-data-gtfs
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-data-v3
  resources:
    requests:
      storage: ${MAP_DATA_GTFS_STORAGE_SIZE:-2Gi}
