apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo 
spec:
  tls:
    - hosts:
        #- ${DOMAIN}
        - podinfo-image.burginfra
      secretName: kube-system/traefik-local-tls # only for local