apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../../infrastructure/_deploy/flux/staging/
  # APPS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - ../../../apps/_deploy/flux/staging/
