apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-test
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: restic-password-secret
      key: RESTIC_PASSWORD
    local:
      mountPath: /backups
  volumeMounts:
    - name: backup-storage
      mountPath: /backups
  volumes:
    - name: backup-storage
      persistentVolumeClaim:
        claimName: rclone-remote-backup-pvc