apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rclone-remote-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: remote-data
  resources:
    requests:
      storage: 10Gi