# this is not managed by flux, apply this manually, run:
# apply-config local
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
configMapGenerator:
   # do not use variables here, it is used to manually create config/secrets map
  - name: podinfo-config-vars
    envs:
      - .env # copy .env.template to .env
    options:
      disableNameSuffixHash: true
