apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-sync-burginfra
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/_deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: burgdev-burginfra
