apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-wodore-production
  namespace: flux-system # do not change!
spec:
  interval: 3m0m
  retryInterval: 10s # Retry quickly when dependencies update or reconciliation fails
  path: "./k8s/apps/wodore/overlays/production"
  prune: false
  #dependsOn:
  #  - name: apps-sync-all-production
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: wd-backend
      namespace: production
  timeout: 3m # Overall timeout for reconciliation including health checks
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: burgdev-burginfra
  postBuild:
    substitute:
      NAMESPACE: "production"
      ENVIRONMENT: "prod"
      ENV_SUBDOMAIN: ""
      # auto updated by fluxcd
      WD_BACKEND_TAG: "0.1.10-alpine" # {"$imagepolicy": "flux-system:wd-backend-production:tag"}
      # https://github.com/wodore/wodore-backend/pkgs/container/wodore-backend
      WD_FRONTEND_TAG: "sha-2d77fda-pwa" # https://github.com/wodore/wodore-frontend-quasar/pkgs/container/wodore-frontend-quasar
      IMAGOR_TAG: "1.6.7" # https://github.com/cshum/imagor/releases
      WD_AVAILABILITY_CRON: "0 0,1,6-23 * * *" # Every hour, except in the night
    substituteFrom:
      - kind: ConfigMap # takes configmap from namespace flux-system
        name: cluster-settings
      - kind: Secret
        name: openbao-configs-heartbeats
        #- kind: Secret
        #  name: wodore-production-config-secret
