apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-wodore-production
  namespace: flux-system # do not change!
spec:
  interval: 3h0s
  retryInterval: 10s # Retry quickly when dependencies update or reconciliation fails
  path: "./k8s/apps/wodore/overlays/production"
  prune: false
  dependsOn:
    - name: apps-sync-all-production
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: wd-backend
      namespace: production
  timeout: 3m # Overall timeout for reconciliation including health checks
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: burgdev-burginfra
  postBuild:
    substitute:
      NAMESPACE: "production"
      ENVIRONMENT: "prod"
      ENV_SUBDOMAIN: ""
      # TODO: move tags to openbao??
      WD_BACKEND_TAG: "edge-alpine"
      # WD_BACKEND_TAG: "sha-cec9031-alpine"
      WD_FRONTEND_TAG: "edge-pwa"
    substituteFrom:
      - kind: ConfigMap # takes configmap from namespace flux-system
        name: cluster-settings
      - kind: Secret
        name: openbao-configs-heartbeats
        #- kind: Secret
        #  name: wodore-production-config-secret
