apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # property-like keys; each key maps to a simple value
  CRUXLI_HOST: "crux.local.gd"
  CRUXLI_EMAIL: "tobias@burgdev.ch"
  BURGDEV_HOST: "burgdev.local.gd"
  BURGDEV_EMAIL: "tobias@burgdev.ch"
  WODORE_HOST: "wodore.local.gd"
  WODORE_EMAIL: "tb@wodore.com"
  WODO_HOST: "wodo.re.local.gd"
  WODO_EMAIL: "tb@wodo.re"
  BURGINFRA_HOST: "infra.local.gd"
  CLUSTER: "local"
  IMMICH_LIBRARY_STORAGE_SIZE: "5Gi"
  IMMICH_EXTERNAL_STORAGE_SIZE: "5Gi"
  IMMICH_DB_STORAGE_SIZE: "2Gi"
