apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # property-like keys; each key maps to a simple value
  CRUXLI_HOST: "crux.local.gd"
  CRUXLI_EMAIL: "tobias@burgdev.ch"
  BURGDEV_HOST: "burgdev.local.gd"
  BURGDEV_EMAIL: "tobias@burgdev.ch"
  BURGINFRA_HOST: "infra.local.gd"
  CLUSTER: "local"
  IMMICH_LIBRARY_STORAGE_SIZE: "5Gi"
  IMMICH_EXTERNAL_STORAGE_SIZE: "5Gi"
  IMMICH_DB_STORAGE_SIZE: "2Gi"
