# any changes need to be reapplied to the cluster:
# just flux deploy local
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: burgdev-burginfra
  namespace: flux-system
spec:
  interval: 15s
  ref:
    branch: flux
