# this is used by flux, do not inclue in any app kustomization.yaml file!
# TODO: add to k8s/flux/*/kustomization.yaml 
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-podinfo-image-local
  namespace: flux-system # do not change!
  
#dependsOn:
    #- name: base-configs  # optional, only if you have one

spec:
  interval: 5s
  path: "./k8s/apps/podinfo-image/overlays/local"
  prune: true
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: local-gitops
  postBuild:
    substitute:
      NAMESPACE: "podinfo-image-local"
      ENVIRONMENT: "local"
    substituteFrom:
      - kind: ConfigMap # takes configmap from namespace flux-system
        name: podinfo-image-config-vars
        # optional: true
