# IMMICH LIBRARY - volsync
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${CLUSTER}-immich-postgres # 'username' for kopia
  namespace: ${NAMESPACE}
spec:
  trigger:
    manual: restore-immich-postgres-${TIMESTAMP}
  kopia:
    repository: volsync-kopia-webdav-secrets

    destinationPVC: immich-postgres-1
    copyMethod: Direct
    enableFileDeletion: false

    # Cache configuration to avoid emptyDir on root filesystem
    cacheCapacity: 10Gi
    cacheAccessModes:
      - ReadWriteOnce

    sourceIdentity:
      sourceName: ${SRC_CLUSTER}-immich-postgres
      sourceNamespace: ${SRC_NAMESPACE}

    moverSecurityContext:
      runAsUser: 26 # potgres
      r0unAsGroup: 26 # tape
      fsGroup: 26
---

