# ImagePolicy for production environment
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: wd-backend
spec:
  imageRepositoryRef:
    name: wd-backend
  policy:
    semver:
      range: "*" # Accept any version
  filterTags:
    pattern: "^${WD_BACKEND_TAG:-latest-alpine}$" # Only match latest-alpine tag
