apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${NAMESPACE}
resources:
  - ../../base
  - backups_volsync.yaml
  - imagepolicy.yaml
patches:
  - path: deployment_patch.yaml
