# this is not managed by flux, apply this manuelly!
#
# kubectl apply -k configs/
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: whoami

configMapGenerator:
- name: whoami-config-vars
  envs:
    - ../.env.local # copy .env.template to .env

generatorOptions:
  disableNameSuffixHash: true