apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  # - ../../infrastructure/longhorn/flux/local/flux-kustom.yaml # -> use openebs lvm
  # Run if longhorn was added and removed again:
  #   kubectl delete validatingwebhookconfiguration longhorn-webhook-validator
  - ../../..infrastructure/volsync/flux/system/flux-kustom.yaml
