apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../flux-system/overlays/dev/
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../../infrastructure/_deploy/dev/
  # APPS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - ../../../apps/_deploy/flux/dev
