apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../cert-manager/flux/system/
  - ../../secret-store-csi-driver/flux/system/
  - ../../openebs/flux/system/
  - ../../volsync/flux/system/
  - ../../csi-driver-rclone/flux/system/
  - ../../vault-secrets-operator/flux/system/
