apiVersion: v1
kind: Namespace
metadata:
    name: development
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
    name: staging
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
    name: production
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
    name: burginfra-system
    annotations:
        kustomize.toolkit.fluxcd.io/prune: disabled
