# PERSISTENT VOLUME =========================================
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-cache-pv
spec:
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/kubernetes/volumes/immich/cache
    type: DirectoryOrCreate