apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-image-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-data
  resources:
    requests:
      storage: 50Mi
