apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-image-data-new
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local
  resources:
    requests:
      storage: 10Mi
