apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-image-fast-local-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-data
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-image-remote-data-pvc3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: remote-data
  resources:
    requests:
      storage: 50Mi
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: podinfo-image-remote-media-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: remote-media
#  resources:
#    requests:
#      storage: 50Mi
