apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-media-pvc-v0 # update deployment.yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v0 # update metadata.name
  resources:
    requests:
      storage: 1Gi