apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kdrive-data-pvc-v0 # update deployment.yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-data-v0 # Changed from kdrive-data-v0 to use existing storage class
  resources:
    requests:
      storage: 50Mi