apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- whoami.yaml

configMapGenerator:
- name: whoami-config
  envs:
    - .env # copy .env.template to .env

replacements:
- source:
    kind: ConfigMap
    name: whoami-config
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Ingress
      name: whoami
    fieldPaths:
    - spec.rules.0.host
