apiVersion: v1
kind: Secret
metadata:
  name: rclone-webdav-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  configData: |
    [webdav]
    type = webdav
    url = ${WEBDAV_URL}
    vendor = other
    user = ${WEBDAV_USERNAME}
    pass = ${WEBDAV_PASSWORD}
---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: remote-media
#provisioner: rclone.csi.veloxpack.io
#parameters:
#  remote: "webdav" 
#  remotePath: "$${pvc.metadata.namespace}/$${pvc.metadata.name}"
#  csi.storage.k8s.io/node-publish-secret-name: "rclone-webdav-secrets"
#  csi.storage.k8s.io/node-publish-secret-namespace: "${NAMESPACE}"
#csi.storage.k8s.io/node-publish-secret-name: "rclone-webdav-secrets"
#csi.storage.k8s.io/node-publish-secret-namespace: "${NAMESPACE}"
#mountOptions:
#  # Enable read/write cache in local disk
#  - vfs-cache-mode=full
#  # Keep directory and file metadata cached longer (less revalidation)
#  - dir-cache-time=12h
#  # Use minimal open file verification to reduce HEAD requests
#  - vfs-read-chunk-size=32M
#  - vfs-read-chunk-size-limit=2G
#  # Cache writes locally until closed (good for large images)
#  - vfs-write-back=5s
#  # Aggressive read-ahead (for streaming)
#  - vfs-read-ahead=128M
#  # Use async reads for multiple files
#  - vfs-cache-poll-interval=5m
#  - vfs-cache-max-size=10G
#  # Avoid unnecessary retries
#  - low-level-retries=3
#  - no-check-certificate
#  - default-permissions=0775
#reclaimPolicy: Delete
#volumeAttributes:
#  file_mode: "665"
#  dir_mode: "775"
#volumeBindingMode: Immediate
#allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: remote-data
provisioner: rclone.csi.veloxpack.io
parameters:
  csi.storage.k8s.io/node-publish-secret-name: "rclone-webdav-secrets"
  csi.storage.k8s.io/node-publish-secret-namespace: "${NAMESPACE}"
  remote: "webdav" 
  remotePath: "$${pvc.metadata.namespace}/$${pvc.metadata.name}"
  default-permissions: "true"
  allow-other: "true"
  umask: "0000" # this is needed!
  #dir-perms: "0777"
  #file-perms: "0666"
  uid: "100"
  gid: "101"
  vfs-cache-mode: "full"
  dir-cache-time: "12h"
  vfs-read-chunk-size: "32M"
  vfs-read-chunk-size-limit: "2G"
  vfs-read-ahead: "128M"
  vfs-write-back: "5s"
  vfs-cache-poll-interval: "5m"
  vfs-cache-max-size: "5G"
# mountOptions:
  # - vfs-cache-max-size=5G
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
