# this is not managed by flux, apply this manuelly!
#
# ./apply-config local
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
configMapGenerator:
  - name: kube-prometheus-stack-config-vars
    envs:
      - .env # copy .env.template to .env
generatorOptions:
  disableNameSuffixHash: true
