apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openbao-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: kms.${BURGINFRA_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openbao-ui
                port:
                  number: 8200
  tls:
    - hosts:
        - kms.${BURGINFRA_HOST}
      secretName: openbao-ui-tls
