apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-backend-media-v0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v2
  resources:
    requests:
      storage: ${WD_BACKEND_MEDIA_STORAGE_SIZE:-2Gi}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-backend-py-cache-v0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-data-v2
  resources:
    requests:
      storage: ${WD_BACKEND_PY_CACHE_STORAGE_SIZE:-1Gi}
