apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wodore-backend-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-${ENVIRONMENT}
  destination:
    name: wodore-backend-envvars
    create: true
    transformation:
      excludeRaw: true
      #excludes: [".*"]
      includes:
        ["DJANGO_.*", "IMAGOR_.*", "HRS_AUTHORIZATION_KEY.*", "FRONTEND_DOMAIN"]
      #templates:
      #  masterkey:
      #    text: "{{ .Secrets.ZITADEL_MASTERKEY }}"
  path: appps/wodore/${NAMESPACE}
---
# DJANO SMTP VARIABLES
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wodore-backend-smtp-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: configs-kv-all
  destination:
    name: wodore-backend-smtp-vars
    create: true
    transformation:
      excludeRaw: true
      includes: ["SMTP_.*"]
  path: configs/smtp
