apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wd-backend-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-${NAMESPACE}
  destination:
    name: wd-backend-envvars
    create: true
    transformation:
      excludeRaw: true
      excludes: ["_.*"]
      includes: ["DJANGO_.*", "HRS_AUTHORIZATION_KEY.*"]
      #templates:
      #  masterkey:
      #    text: "{{ .Secrets.ZITADEL_MASTERKEY }}"
  path: apps/wodore/${NAMESPACE}
---
# DJANO SMTP VARIABLES
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wd-backend-smtp-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: configs-kv-all
  destination:
    name: wd-backend-smtp-vars
    create: true
    transformation:
      excludeRaw: true
      excludes: [".*"]
      #includes: ["SMTP_.*"]
      templates:
        EMAIL_HOST:
          text: "{{ .Secrets.SMTP_HOST }}"
        EMAIL_HOST_PASSWORD:
          text: "{{ .Secrets.SMTP_PASSWORD }}"
        EMAIL_HOST_USER:
          text: "{{ .Secrets.SMTP_USERNAME }}"
        EMAIL_PORT:
          text: "{{ .Secrets.SMTP_HOST_PORT }}"
        EMAIL_USE_SSL:
          text: "{{ .Secrets.SMTP_SSL }}"
        EMAIL_USE_TLS:
          text: "{{ .Secrets.SMTP_TLS }}"
  path: configs/smtp
