apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h0s
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: "0.22.*"
  install:
    createNamespace: false
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    monitoring:
      # deploy prometheus stack for this (currently disabled)
      podMonitorEnabled: false
      grafanaDashboard:
        create: false
  interval: 1h0s
