apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-production-config-secret
  namespace: flux-system
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-flux
  destination:
    name: immich-production-config-secret # the name of the K8s Secret
    create: true
    transformation:
      excludeRaw: true # exclue _raw field
  path: apps/immich/production # OpenBao KV path
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-immich-production
  namespace: flux-system # do not change!
spec:
  interval: 3h0s
  retryInterval: 10s # Retry quickly when dependencies update or reconciliation fails
  path: "./k8s/apps/immich/overlays/production"
  prune: false
  dependsOn:
    - name: apps-sync-all-production
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: burgdev-burginfra
  postBuild:
    substitute:
      NAMESPACE: "production"
      ENVIRONMENT: "prod"
      ENV_SUBDOMAIN: ""
    substituteFrom:
      - kind: ConfigMap # takes configmap from namespace flux-system
        name: cluster-settings
      - kind: Secret
        name: immich-production-config-secret
      - kind: Secret
        name: openbao-configs-smtp-cruxli
      - kind: Secret
        name: openbao-configs-heartbeats
