#!/bin/bash
set -euo pipefail

USAGE="Usage: $0"

ENVIRONMENT=system

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
ROOT_DIR="$(realpath $SCRIPT_DIR/../../../)"
. $ROOT_DIR/scripts/_base.sh
cd $SCRIPT_DIR

#kubeconfig_check $ENVIRONMENT

config_path=$(realpath --relative-to="." configs/$ENVIRONMENT)
title "Generate configuration${rst} $(s d "from $(s u $config_path)")"
echo "$(s d kubectl apply -k $config_path)"
kubectl apply -k $config_path
cd -
success "DONE"
