# this is used by flux, do not inclue in any app kustomization.yaml file!
# TODO: add to k8s/flux/*/kustomization.yaml 
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-traefik-local
  namespace: flux-system # do not change!
  
#dependsOn:
    #- name: base-configs  # optional, only if you have one

spec:
  interval: 1h0s
  path: "./k8s/infrastructure/traefik/overlays/local"
  prune: true
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: local-gitops
  postBuild:
    substitute:
      NAMESPACE: "traefik-local" # probably not used, kube-system per default
      ENVIRONMENT: "local"
      EMAIL: "tobias@burgdev.ch"
