# Images: https://github.com/perfectra1n/volsync/pkgs/container/volsync
# Values: https://github.com/perfectra1n/volsync/tree/main/helm/volsync
manageCRDs: true
metrics:
  disableAuth: true
image:
  #repository: ghcr.io/perfectra1n/volsync
  #tag: "0.16.13"
  repository: ghcr.io/burgdev/volsync
  tag: "latest"
  image: ""
kopia:
  #repository: ghcr.io/perfectra1n/volsync
  #tag: "0.16.13"
  repository: ghcr.io/burgdev/volsync
  #tag: "latest"
  tag: "sha256:4e379ab24cb5a25d4d5998a175e762dedd38cd8e1701799b5a366a27a62cba6e"
  image: ""
rclone:
  repository: ghcr.io/perfectra1n/volsync
  tag: "0.16.13"
  image: ""
restic:
  repository: ghcr.io/perfectra1n/volsync
  tag: "0.16.13"
  image: ""
rsync:
  repository: ghcr.io/perfectra1n/volsync
  tag: "0.16.13"
  image: ""
rsync-tls:
  repository: ghcr.io/perfectra1n/volsync
  tag: "0.16.13"
  image: ""
syncthing:
  repository: ghcr.io/perfectra1n/volsync
  tag: "0.16.13"
  image: ""
