# this is not managed by flux, apply this manuelly!
#
# kubectl apply -k configs/
#
namespace: flux-system
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: webdav-credentials
    envs:
      - .env.secret
    options:
      disableNameSuffixHash: true
