apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${CLUSTER}-openbao-data # 'username' for kopia
  namespace: ${NAMESPACE}
spec:
  trigger:
    manual: restore-${TIMESTAMP}
  kopia:
    repository: volsync-kopia-webdav-secrets
    destinationPVC: data-openbao-0
    copyMethod: Direct
    enableFileDeletion: true

    sourceIdentity:
      sourceName: ${SRC_CLUSTER}-openbao-data
      sourceNamespace: ${SRC_NAMESPACE}

    moverSecurityContext:
      runAsUser: 100
      runAsGroup: 1000
      fsGroup: 1000
