apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.default.acme.email=${EMAIL}"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      #web:
      #  exposedPort: 80
      #websecure:
      #  exposedPort: 443
    tls:
      stores:
        default:
          defaultCertificate:
            secretName: traefik-local-tls
      options:
        default:
          minVersion: VersionTLS12
          sniStrict: true