# this is used by flux, do not include in any app kustomization.yaml file!
# TODO: add to k8s/flux/*/kustomization.yaml 
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-volsync-system
  namespace: flux-system # do not change!
#dependsOn:
#- name: base-configs  # optional, only if you have one
spec:
  interval: 1h0s
  path: "./k8s/infrastructure/volsync/helm/overlays/local"
  prune: true
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: git-burginfra
  postBuild:
    substitute:
      NAME: "volsync"
      NAMESPACE: "burginfra-system"
      ENVIRONMENT: "system"
      REPO_INTERVAL: "1h0s"
      SOURCE_INTERVAL: "1h0s"
      CHART_VERSION: "0.17.x"