apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../traefik/flux/staging/
  # - ../../openbao/flux/staging/
  #- ../../k8up/flux/local/flux-kustom.yaml
  #- ../../cert-manager/flux/local/flux-kustom.yaml
  #- ../../kube-prometheus-stack/flux/local/flux-kustom.yaml
