apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - kustomization-infra.yaml
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  #- ../../infrastructure/traefik/
  - ../../infrastructure/longhorn/base/
  #- ../../infrastructure/rclone/base # no kustomize yet
  # APPS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #- ../../apps/immich/overlays/local/
  - ../../apps/whoami/flux/local/kustomization.yaml
  - ../../apps/podinfo-image/flux/local/kustomization.yaml
  #- ../../flux/local
