apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  #- kustomization-infra.yaml
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../infrastructure/traefik/flux/local/kustomization.yaml
  - ../../infrastructure/longhorn/base/
  - ../../infrastructure/cert-manager/flux/local/kustomization.yaml
  #- ../../infrastructure/rclone/base # no kustomize yet
  # APPS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - ../../apps/podinfo-image/flux/local/kustomization.yaml
