apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      ipFamilyPolicy: PreferDualStack
      ipFamilies:
        - IPv4
        - IPv6
    ports:
      web:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
      #web:
      #  exposedPort: 80
      #websecure:
      #  exposedPort: 443
