# this is not managed by flux, apply this manuelly!
namespace: flux-system
secretGenerator:
  - name: rclone-webdav-credentials
    envs:
      - .env.secret
    options:
      disableNameSuffixHash: true
