# Note: We don't manage the postgres superuser password
# CloudNativePG auto-generates it and stores it in a secret
# We only need the zitadel application user credentials
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-postgres-credentials
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-postgres-credentials
    create: true
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      excludes: ".*"
      templates:
        username:
          text: "zitadel"
        password:
          text: "{{ .Secrets.ZITADEL_DATABASE_POSTGRES_USER_PASSWORD }}"
  path: infrastructure/zitadel/${NAMESPACE}
