# DATABASE -- basic-auth
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-postgres-credentials
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-postgres-credentials
    create: true
    labels:
      cnpg.io/reload: "true"
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        username:
          text: "{{ .Secrets.POSTGRES_USERNAME }}"
        password:
          text: "{{ .Secrets.POSTGRES_PASSWORD }}"
  path: infrastructure/zitadel/${NAMESPACE}
---
# MASTERKEY -- masterkey
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-masterkey
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-masterkey
    create: true
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        masterkey:
          text: "{{ .Secrets.ZITADEL_MASTERKEY }}"
  path: infrastructure/zitadel/${NAMESPACE}
---
# FIST ORG CREDENTIALS -- basic-auth
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-firstinstance-credentials
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-firstinstance-credentials
    create: true
    type: kubernetes.io/basic-auth
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        password:
          text: "{{ .Secrets.ZITADEL_FIRST_HUMAN_PASSWORD }}"
        username:
          text: "{{ .Secrets.ZITADEL_FIRST_HUMAN_USERNAME }}"
  path: infrastructure/zitadel/${NAMESPACE}
---
# ZITADEL ENV VARIABLES
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-envvars
    create: true
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        ZITADEL_DATABASE_POSTGRES_USER_PASSWORD:
          text: "{{ .Secrets.POSTGRES_PASSWORD }}"
        ZITADEL_DATABASE_POSTGRES_USER_USERNAME:
          text: "{{ .Secrets.POSTGRES_USERNAME }}"
        ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD:
          text: "{{ .Secrets.POSTGRES_PASSWORD }}"
        ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME:
          text: "{{ .Secrets.POSTGRES_USERNAME }}"
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD:
          text: "{{ .Secrets.ZITADEL_FIRST_HUMAN_PASSWORD }}"
        ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME:
          text: "{{ .Secrets.ZITADEL_FIRST_HUMAN_USERNAME }}"
  path: infrastructure/zitadel/${NAMESPACE}
