# MASTERKEY -- masterkey
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-masterkey
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-masterkey
    create: true
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        masterkey:
          text: "{{ .Secrets.ZITADEL_MASTERKEY }}"
  path: infrastructure/zitadel/${NAMESPACE}
---
# ZITADEL ENV VARIABLES
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${ENVIRONMENT}
  destination:
    name: zitadel-envvars
    create: true
    transformation:
      excludeRaw: true
      excludes: ["ZITADEL_MASTERKEY"]
      includes: ["ZITADEL_.*"]
  path: infrastructure/zitadel/${NAMESPACE}
---
# ZITADEL SMTP VARIABLES
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-smtp-vars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: configs-kv-all
  destination:
    name: zitadel-smtp-vars
    create: true
    transformation:
      excludeRaw: true
      includes: ["SMTP_.*"]
  path: configs/smtp_burgdev
