apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: zitadel-config-secret
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: infra-kv-${NAMESPACE}
  destination:
    name: zitadel-config-secret
    create: true
    transformation:
      excludeRaw: true
  path: infrastructure/zitadel/${NAMESPACE}
