apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # BURGDEV
  - ../../podinfo/overlays/production/
  - ../../umami/overlays/production/
  # CRUXLI
  - ../../immich/flux/production
  # WODORE
  - ../../wodore/flux/production
