apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - imageupdateautomation.yaml
  # BURGDEV
  - ../../podinfo/overlays/production/
  - ../../umami/overlays/production/
  # CRUXLI
  - ../../immich/flux/production/
  # WODORE
  - ../../wodore/flux/production/
  #- ../../valhalla/overlays/production/
  #- ../../graphhopper/overlays/production/
  - ../../map-data/overlays/production/
