apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/imagor/overlays/production
  - ../../apps/backend/overlays/production
  - ../../apps/frontend/overlays/production
  - ../../apps/martin/overlays/production
