apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-openbao-system
  namespace: flux-system # do not change!
#dependsOn:
#- name: base-configs  # optional, only if you have one
spec:
  interval: 3h0s
  retryInterval: 10s # Retry quickly when dependencies update or reconciliation fails
  path: "./k8s/infrastructure/openbao/overlays/system"
  prune: false
  dependsOn:
    - name: infra-openebs-system
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: burgdev-burginfra
  postBuild:
    substitute:
      NAMESPACE: "burginfra-system"
      ENVIRONMENT: "system"
    substituteFrom:
      - kind: ConfigMap # takes configmap from namespace flux-system
        name: cluster-settings
      - kind: Secret
        name: openbao-configs-heartbeats
