apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: valhalla
  app.kubernetes.io/component: routing
  app.kubernetes.io/environment: ${ENVIRONMENT}
  app.kubernetes.io/part-of: apps
  app.kubernetes.io/managed-by: flux
resources:
  - pvc.yaml
  - job-download.yaml
  - job-build.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: valhalla-download-scripts
    options:
      disableNameSuffixHash: true
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - scripts/download-osm.sh
      - scripts/download-gtfs.sh
      - scripts/download-elevation.sh
