# this is used by flux, do not include in any app kustomization.yaml file!
# TODO: add to k8s/flux/*/kustomization.yaml 
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-csi-driver-rclone-local
  namespace: flux-system # do not change!
spec:
  interval: 1h0s
  path: "./k8s/infrastructure/csi-driver-rclone/helm/overlays/local"
  prune: true
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: git-burginfra
  postBuild:
    substitute: # use the same values for all kustomizations
      NAME: "csi-driver-rclone"
      NAMESPACE: "csi-driver-rclone-local"
      ENVIRONMENT: "local"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-csi-driver-rclone-local
  namespace: flux-system # do not change!
spec:
  interval: 1h0s
  path: "./k8s/infrastructure/csi-driver-rclone/overlays/local"
  prune: true
  dependsOn:
  - name: helm-csi-driver-rclone-local
  sourceRef: # k8s/clusters/local/flux-system/gotk-sync.yaml
    kind: GitRepository
    name: git-burginfra
  postBuild:
    substitute:
      NAME: "csi-driver-rclone"
      NAMESPACE: "csi-driver-rclone-local"
      ENVIRONMENT: "local"
    substituteFrom:
      - kind: Secret
        name: webdav-credentials
        optional: false
      
