apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-kdrive-data-pvc-v0 # update deployment.yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kdrive-data-v0 # update metadata.name
  resources:
    requests:
      storage: 50Mi

