apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-fast-media-pvc-v3 # update deployment.yaml
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v3 # update metadata.name
  resources:
    requests:
      storage: 1Gi
