apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: podinfo-config-secret
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-${NAMESPACE} # either default or staging
  #vaultAuthRef: apps-kv-all # either default or staging
  destination:
    name: podinfo-config-secret # the name of the K8s Secret
    create: true
    transformation:
      excludeRaw: true # exclue _raw field
  path: apps/podinfo/${NAMESPACE} # OpenBao KV path

