apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: podinfo-secret1
  namespace: staging
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: staging # either default or staging
  destination:
    name: podinfo-secret1 # the name of the K8s Secret
    create: true
  path: podinfo # OpenBao KV path

