# k8s/immich/overlays/local/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - backups_volsync.yaml
  - backup_volsync_db.yaml
namespace: production
