apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../infrastructure/traefik
  - ../../infrastructure/longhorn/base
  - ../../infrastructure/rclone/base
  # APPS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - ../../apps/immich/overlay/local
  - ../../apps/whoami/
