apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # INFRASTRUCTURE ~~~~~~~~~~~~~~~~~~~~~~~
  - ../../infrastructure/traefik/
  - ../../infrastructure/longhorn/base/
  #- ../../infrastructure/rclone/base # no kustomize yet
  # APPS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - ../../apps/immich/overlays/local/
  - ../../apps/whoami/
