apiVersion: apps/v1
kind: Deployment
metadata:
  name: wd-imagor
spec:
  replicas: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wd-imagor
  template:
    metadata:
      labels:
        app: wd-imagor
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: wd-imagor
          image: shumc/imagor:1.6.6
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: PORT
              value: "8000"
            - name: DEBUG
              value: "0"
            - name: IMAGOR_AUTO_WEBP
              value: "1"
            - name: IMAGOR_AUTO_ACIF
              value: "1"
            - name: IMAGOR_SIGNER_TYPE
              value: "sha256"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
