apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-imagor-result-pvc-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v2
  resources:
    requests:
      storage: ${WODORE_IMAGOR_STORAGE_SIZE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-imagor-storage-pvc-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v2
  resources:
    requests:
      storage: ${WODORE_IMAGOR_STORAGE_SIZE}
---
# TODO: move to wodore backend
# Shared with backend for media files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-backend-media-pvc-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v2
  resources:
    requests:
      storage: ${WODORE_MEDIA_STORAGE_SIZE}
