apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-imagor-result-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v3
  resources:
    requests:
      storage: ${WD_IMAGOR_STORAGE_SIZE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wd-imagor-storage-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-local-media-v3
  resources:
    requests:
      storage: ${WD_IMAGOR_STORAGE_SIZE}
