apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wd-imagor-config-secret
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-${NAMESPACE}
  destination:
    name: wd-imagor-config-secret # the name of the K8s Secret
    create: true
    transformation:
      excludeRaw: true # exclue _raw field
      excludes: [".*"]
      #includes: ["IMAGOR_.*"]
      templates:
        IMAGOR_SECRET:
          text: "{{ .Secrets.IMAGOR_KEY }}"
  path: apps/wodore/${NAMESPACE} # OpenBao KV path
