#!/bin/bash
set -e

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Generate certificates if they don't exist
DOMAIN=$(grep -m1 '^DOMAIN=' "$SCRIPT_DIR/.env" | cut -d '=' -f2-)
$SCRIPT_DIR/../../scripts/bin/bui-local-certs "$DOMAIN"

$SCRIPT_DIR/update-immich-values

# Apply kustomization
kubectl apply -k "$SCRIPT_DIR"
