# PERSISTENT VOLUME =========================================
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-cache-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /home/tobias/mnt/k8s/immich/cache
    #path: /mnt/kubernetes/volumes/immich/cache
    type: DirectoryOrCreate
---
# PERSISTEN VOLUME CLAIM =====================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path   # or whatever StorageClass you use in k3s
  volumeName: immich-cache-pv
---
# IMMICH DATABASE ========================= immich-database ==
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-cache
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-cache
  template:
    metadata:
      labels:
        app: immich-cache
    spec:
      containers: # TODO
        - name: immich-valkey
          image: "docker.io/valkey/valkey:9.0-alpine3.22"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: valkeydata
              mountPath: /data
          resources: {}
          command: ["valkey-server"]
          args: ["--save", "60 1", "--loglevel", "warning", "--appendonly", "yes"]
      volumes:
        - name: valkeydata
          persistentVolumeClaim:
            claimName: immich-cache
---
kind: Service
apiVersion: v1
metadata:
  name: immich-cache
  namespace: immich
  labels:
    app: immich-cache
spec:
  type: ClusterIP
  selector:
    app: immich-cache
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: 6379
      protocol: TCP