# IMMICH NAMESPACE ================================= immich ==
apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
# PRESISTEND VOLUME ===========================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /home/tobias/mnt/k8s/immich/library
    #path: /mnt/kubernetes/volumes/immich/server/library
    type: DirectoryOrCreate
---
# PRESISTEND VOLUME CLAIM =====================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path   # or whatever StorageClass you use in k3s
  volumeName: immich-library-pv
---
# IMMICH HELM ================================ immich-server ==
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: immich
  namespace: immich
spec:
  chart: immich
  repo: https://immich-app.github.io/immich-charts
  version: 0.9.3
  targetNamespace: immich
  valuesContent: ""  # Will be replaced by kustomize, changes are made in `immich-values.yaml`
---
# IMMICH INGRESS =============================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
spec:
  tls:
    - hosts:
        - $DOMAIN
      secretName: traefik-me-tls # only for local
  rules:
    - host: $DOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 2283