apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: wd-frontend-envvars
spec:
  type: kv-v2
  mount: kv
  vaultAuthRef: apps-kv-${NAMESPACE}
  destination:
    name: wd-frontend-envvars
    create: true
    transformation:
      excludeRaw: true
      includes: ["WODORE_.*"]
      templates:
        WODORE_API_HOST:
          text: "https://hub.${ENV_SUBDOMAIN}${WODORE_HOST}"
        WODORE_URL:
          text: "https://${ENV_SUBDOMAIN}${WODORE_HOST}"
        WODORE_DOMAIN:
          text: "${ENV_SUBDOMAIN}${WODORE_HOST}"
        WODORE_UMAMI_WEBSITE_URL:
          text: "https://stats.${ENV_SUBDOMAIN}${WODORE_HOST}"
        WODORE_IMAGOR_URL:
          text: "https://img.${ENV_SUBDOMAIN}${WODORE_HOST}"
        WODORE_IMAGOR_REPLACE_API_HOST_MEDIA:
          text: "wd"
        WODORE_APP_NAME:
          text: ${WD_FRONTEND_APP_NAME:-Wodore}
  path: apps/wodore/${NAMESPACE}
