apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # BURGDEV
  - ../../podinfo/overlays/staging/
  # WODORE
  - ../../wodore/flux/staging/
  # ROUTING
  # - ../../graphhopper/overlays/staging/
