apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${CLUSTER}-podinfo-data # 'username' for kopia
  namespace: ${NAMESPACE}
spec:
  trigger:
    manual: restore-podinfo-data-${TIMESTAMP}
  kopia:
    repository: volsync-kopia-webdav-secrets
    destinationPVC: podinfo-fast-data-pvc-v2
    copyMethod: Direct
    enableFileDeletion: true
    # Non-negative integer that specifies how many snapshots to skip before selecting one to restore from.
    # When set to 0 (the default), the latest snapshot is used.
    # When set to 1, the second newest snapshot is used (skipping 1 snapshot), and so on.
    # This parameter can be combined with restoreAsOf to skip snapshots from a specific point in time.
    previous: 0
    restoreAsOf: ${RESTORE_AS_OF}

    sourceIdentity:
      sourceName: ${SRC_CLUSTER}-podinfo-data
      sourceNamespace: ${SRC_NAMESPACE}

    moverSecurityContext:
      runAsUser: 100
      runAsGroup: 1000
      fsGroup: 1000
